"""Add LoginAttempt model for brute-force protection

Revision ID: 781a38b546bd
Revises: c8dcfb08146f
Create Date: 2025-11-01 09:56:29.449229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781a38b546bd'
down_revision: Union[str, None] = 'c8dcfb08146f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=200), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_login_attempts_attempted_at', 'login_attempts', ['attempted_at'], unique=False)
    op.create_index('idx_login_attempts_email', 'login_attempts', ['email'], unique=False)
    op.create_index('idx_login_attempts_ip', 'login_attempts', ['ip_address'], unique=False)
    # Note: Unique constraints were already added in previous migration
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Unique constraints handled by previous migration
    op.drop_index('idx_login_attempts_ip', table_name='login_attempts')
    op.drop_index('idx_login_attempts_email', table_name='login_attempts')
    op.drop_index('idx_login_attempts_attempted_at', table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
