"""Initial schema with all tables

Revision ID: f446a5a2d95f
Revises: 
Create Date: 2025-11-01 09:54:57.951227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f446a5a2d95f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_attendance_child_date', table_name='attendance')
    op.drop_index('uq_daily_reports_child_date', table_name='daily_reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_daily_reports_child_date', 'daily_reports', ['child_id', 'date'], unique=False)
    op.create_index('uq_attendance_child_date', 'attendance', ['child_id', 'date'], unique=False)
    # ### end Alembic commands ###
